name: Keep Codespace Alive

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Keep-Alive Request
        run: curl http://localhost:8000
